test if java second level fails and java first level successes with server first level cetificate

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -22,5 +22,31 @@ function server_second_level_cert_and_key_java_client_first_level_cert_success()
  echo $CLIENT_OUT | grep -q "I hear you" && echo $0 "Success" || echo $1 "Failure"
 }
 
+function server_first_level_cert_and_key_java_client_first_level_cert_success()
+{
+ killall server &> /dev/null
+ ../server/server ../ca/ca-cert.pem ../ca/ca-key.pem &> /dev/null &
+
+ sleep 1
+ CLIENT_OUT=$(cd ../java-client && java SslClient ../ca/ca-cert.pem)
+ 
+ echo $CLIENT_OUT | grep -q "I hear you" && echo $0 "Success" || echo $1 "Failure"
+}
+
+function server_first_level_cert_and_key_java_client_second_level_cert_failure()
+{
+ killall server &> /dev/null
+ ../server/server ../ca/ca-cert.pem ../ca/ca-key.pem &> /dev/null &
+
+ sleep 1
+ CLIENT_OUT=$(cd ../java-client && java SslClient ../server/foo-cert.pem 2>&1)
+ 
+ echo $CLIENT_OUT \
+   | grep -q "unable to find valid certification path to requested target" \
+   && echo $0 "Success" || echo $0 "Failure"
+}
+
 server_second_level_cert_and_key_java_client_second_level_cert_success
 server_second_level_cert_and_key_java_client_first_level_cert_success
+server_first_level_cert_and_key_java_client_first_level_cert_success
+server_first_level_cert_and_key_java_client_second_level_cert_failure
